version: '3.7'

services:
  thehive:
    image: thehiveproject/thehive4:latest
    container_name: thehive
    ports:
      - 9000:9000
    volumes:
      - ./thehive/application.conf:/etc/thehive/application.conf
      - ./thehive/db:/opt/thp/thehive/db
      - ./thehive/data:/opt/thp/thehive/data
      - ./thehive/index:/opt/thp/thehive/index
    networks:
      - network
  
  cortex:
    image: thehiveproject/cortex:latest
    container_name: cortex
    ports:
      - 9001:9001
    volumes:
      - ./cortex/application.conf:/etc/cortex/application.conf
      - ./cortext/jobs:/opt/cortex/jobs
      - ./cortex/analyzers:/opt/cortex/analyzers
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - network

#  n8n:
#    image: n8nio/n8n
#    container_name: n8n
#    ports:
#      - 5678:5678
#    command: n8n start
#    environment:
#      - DB_TYPE=postgresdb
#      - DB_POSTGRESDB_HOST=postgres
#      - DB_POSTGRESDB_PORT=5432
#      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
#      - DB_POSTGRESDB_USER=${POSTGRES_USER}
#      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
#      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
#      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
#      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
#    volumes:
#      - ./n8n/.n8n:/root/.n8n
#      - ./n8n/workflows:/opt/workflows
#    networks:
#      -  network
    
#  postgres:
#    image: postgres:latest
#    container_name: postgres
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=${POSTGRES_DB}
#    volumes:
#      - ./postgres/data:/var/lib/postgresql/data
#    networks:
#      - network
    
networks:
  network:
    name: sirp_network
